import type { ShopItem } from './index.js';

/** Full RD shop catalog — soft currency + IAP stubs */
export const FULL_SHOP_CATALOG: ShopItem[] = [
  // —— Personajes ——
  {
    id: 'skin_char_default',
    category: 'character',
    name: 'Corredor RD',
    description: 'Camisa blanca, gorra bandera, mochila RD.',
    priceCoins: 0,
    previewColor: '#F5F5F5',
    icon: 'runner',
    rarity: 'common',
  },
  {
    id: 'skin_char_merengue',
    category: 'character',
    name: 'Merengue',
    description: 'Ritmo caribeño en cada salto.',
    priceCoins: 1200,
    previewColor: '#C62828',
    icon: 'runner',
    rarity: 'rare',
  },
  {
    id: 'skin_char_dembow',
    category: 'character',
    name: 'Dembow Flow',
    description: 'Velocidad urbana de la capital.',
    priceCoins: 1800,
    previewColor: '#6A1B9A',
    icon: 'runner',
    rarity: 'rare',
  },
  {
    id: 'skin_char_colmado',
    category: 'character',
    name: 'Rey del Colmado',
    description: 'Del barrio pa’ las vías.',
    priceCoins: 2200,
    previewColor: '#F5C542',
    icon: 'runner',
    rarity: 'epic',
  },
  {
    id: 'skin_char_omsa',
    category: 'character',
    name: 'Inspector OMSA',
    description: 'Uniforme azul tránsito capitalino.',
    priceCoins: 2500,
    previewColor: '#1565C0',
    icon: 'runner',
    rarity: 'epic',
  },
  // —— Mochilas ——
  {
    id: 'skin_backpack_rd',
    category: 'backpack',
    name: 'Mochila RD',
    description: 'Clásica negra con letras RD.',
    priceCoins: 0,
    previewColor: '#111111',
    icon: 'backpack',
    rarity: 'common',
  },
  {
    id: 'skin_backpack_guagua',
    category: 'backpack',
    name: 'Mochila Guagua',
    description: 'Inspirada en la ruta 27.',
    priceCoins: 800,
    previewColor: '#1565C0',
    icon: 'backpack',
    rarity: 'rare',
  },
  {
    id: 'skin_backpack_bandera',
    category: 'backpack',
    name: 'Mochila Bandera',
    description: 'Rojo, blanco y azul a la espalda.',
    priceCoins: 1100,
    previewColor: '#D5162C',
    icon: 'backpack',
    rarity: 'rare',
  },
  {
    id: 'skin_backpack_oro',
    category: 'backpack',
    name: 'Mochila Oro',
    description: 'Brilla como el sol de SD.',
    priceCoins: 2000,
    previewColor: '#FFD54F',
    icon: 'backpack',
    rarity: 'epic',
  },
  // —— Patinetas ——
  {
    id: 'skin_skate_basic',
    category: 'skateboard',
    name: 'Patineta Barrio',
    description: 'La de siempre pa’ esquivar.',
    priceCoins: 0,
    previewColor: '#333333',
    icon: 'skate',
    rarity: 'common',
  },
  {
    id: 'skin_skate_republica',
    category: 'skateboard',
    name: 'Skate República',
    description: 'Llamas y bandera.',
    priceCoins: 1200,
    previewColor: '#F9A825',
    icon: 'skate',
    rarity: 'rare',
  },
  {
    id: 'skin_skate_neon',
    category: 'skateboard',
    name: 'Skate Neón',
    description: 'Trail luminoso al activar.',
    priceCoins: 2100,
    previewColor: '#00E5FF',
    icon: 'skate',
    rarity: 'epic',
  },
  {
    id: 'skin_skate_legend',
    category: 'skateboard',
    name: 'Skate Quítate',
    description: 'Edición ¡Quítate del medio!',
    priceCoins: 3500,
    previewColor: '#FF6D00',
    icon: 'skate',
    rarity: 'legend',
  },
  // —— Ropa (street loot unlocks + shop) ——
  {
    id: 'clothes_gorra_rd',
    category: 'clothes',
    name: 'Gorra Bandera',
    description: 'Se recoge en las calles o se compra.',
    priceCoins: 400,
    previewColor: '#FFFFFF',
    icon: 'hat',
    rarity: 'common',
  },
  {
    id: 'clothes_camiseta_27',
    category: 'clothes',
    name: 'Camiseta Ruta 27',
    description: 'Estilo OMSA / colmado.',
    priceCoins: 650,
    previewColor: '#1D63C7',
    icon: 'shirt',
    rarity: 'common',
  },
  {
    id: 'clothes_jeans_azul',
    category: 'clothes',
    name: 'Jeans Capital',
    description: 'Azul profundo santo.',
    priceCoins: 700,
    previewColor: '#1E3A8A',
    icon: 'pants',
    rarity: 'common',
  },
  {
    id: 'clothes_tenis_rojo',
    category: 'clothes',
    name: 'Tenis Rojo/Blanco',
    description: 'Para correr sin freno.',
    priceCoins: 900,
    previewColor: '#E6303F',
    icon: 'shoe',
    rarity: 'rare',
  },
  {
    id: 'clothes_chaqueta_merengue',
    category: 'clothes',
    name: 'Chaqueta Merengue',
    description: 'Fit de fiesta en la avenida.',
    priceCoins: 1500,
    previewColor: '#C1272D',
    icon: 'shirt',
    rarity: 'epic',
  },
  // —— Armas arcade (street power, satirical clear) ——
  {
    id: 'weapon_bate',
    category: 'weapon',
    name: 'Bate de Colmado',
    description: '1 carga arcade para limpiar vía.',
    priceCoins: 500,
    previewColor: '#8B5A2B',
    icon: 'bat',
    rarity: 'common',
  },
  {
    id: 'weapon_botella',
    category: 'weapon',
    name: 'Botella de Malta',
    description: 'Power-up urbano caricaturesco.',
    priceCoins: 450,
    previewColor: '#C62828',
    icon: 'bottle',
    rarity: 'common',
  },
  {
    id: 'weapon_paraguas',
    category: 'weapon',
    name: 'Paraguas Tormenta',
    description: 'Cuando llueve en la capital.',
    priceCoins: 800,
    previewColor: '#37474F',
    icon: 'umbrella',
    rarity: 'rare',
  },
  {
    id: 'weapon_megafono',
    category: 'weapon',
    name: 'Megáfono RD',
    description: 'Grita ¡quítate del medio!',
    priceCoins: 1400,
    previewColor: '#F5C542',
    icon: 'megaphone',
    rarity: 'epic',
  },
  {
    id: 'weapon_bandera',
    category: 'weapon',
    name: 'Bandera Tricolor',
    description: 'Limpia el carril con orgullo.',
    priceCoins: 2000,
    previewColor: '#0033A0',
    icon: 'flag',
    rarity: 'legend',
  },
  // —— Monedas IAP ——
  {
    id: 'coins_pack_small',
    category: 'coins',
    name: '1,000 Monedas',
    description: 'Pack rápido.',
    iapProductId: 'com.cruzard.coins_1000',
    previewColor: '#FFD54F',
    icon: 'coin',
    rarity: 'common',
  },
  {
    id: 'coins_pack_medium',
    category: 'coins',
    name: '5,000 Monedas',
    description: 'Mejor valor.',
    iapProductId: 'com.cruzard.coins_5000',
    previewColor: '#FFC107',
    icon: 'coin',
    rarity: 'rare',
  },
  {
    id: 'coins_pack_large',
    category: 'coins',
    name: '12,000 Monedas',
    description: 'Pack capitalino.',
    iapProductId: 'com.cruzard.coins_12000',
    previewColor: '#FF8F00',
    icon: 'coin',
    rarity: 'epic',
  },
  // —— Ofertas ——
  {
    id: 'offer_remove_ads',
    category: 'offer',
    name: 'Quitar Anuncios',
    description: 'Juego limpio sin interrupciones.',
    iapProductId: 'com.cruzard.remove_ads',
    previewColor: '#6A1B9A',
    icon: 'star',
    rarity: 'legend',
  },
  {
    id: 'offer_starter',
    category: 'offer',
    name: 'Pack Arranque RD',
    description: '2,000 monedas + 5 patinetas (IAP stub).',
    iapProductId: 'com.cruzard.starter',
    previewColor: '#2E7D32',
    icon: 'gift',
    rarity: 'epic',
  },
];
